[DEFAULT]

; If you want to add custom values/settings, then check the values/settings you want to change in "config.default.ini"
; and insert them below to persist future driver updates.

; Example (remove the semicolon ";" to uncomment and activate the value/setting):
; MAX_BATTERY_CHARGE_CURRENT = 50.0
; MAX_BATTERY_DISCHARGE_CURRENT = 60.0

DEVICES = /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AG0KG1HS-if00-port0

#POLL_INTERVAL = 2000

BLOCK_ON_DISCONNECT = True

MAX_BATTERY_CHARGE_CURRENT = 65
MAX_BATTERY_DISCHARGE_CURRENT = 130

#BMS_TYPE = EcsBmv

AUTO_DETECT_BMS = False


BMS_TYPE=
EXCLUDED_DEVICES = /dev/ttyUSB1

#driver = ecs_bmv
#port = /dev/ttyUSB1

#baudrate = 19200
#timeout = 1

#SLAVE_ADDRESSES = 1,100, 101, 200
#BATTERY_ADDRESSES = 1,100,101,200
LOGGING = INFO